import React from "react";
import "../assets/css/how-to-use.css";
import proImg1 from "../assets/images/zapper.jpg";
import proImg2 from "../assets/images/silver.jpg";
import proImg3 from "../assets/images/pulsar.jpg";
import pdf from "../assets/images/hindi.pdf";

export default function HowToUse() {
  return (
    <div className="how-to-use">
      <h2>How to use Our Product</h2>
      <div className="p-use">
        <div className="step1">
          <div>
            <img src={proImg1} alt="pro-image" width="100%" />
          </div>

          <div>
            <p className="use-title">How To Use Zapper</p>
            <p className="use-desc">
              Take two cotton clothes or napkins before starting the zap
              process. Rinse them in salt mixed water. Roll each of these cotton
              clothes drenched in salty water on each of the copper pies. It
              makes the flow of the electric current better. Besides, the
              current generated by the Zapper is so low that it would hardly
              reach the body if the clothes are not drenched in salty water.
            </p>
            <a href={pdf} download>
              Click Here For pdf Book
            </a>
          </div>
        </div>

       

        <div className="step3">
          <div>
            <img src={proImg3} alt="pro-image" width="100%" />
          </div>

          <div>
            <p className="use-title">How To Use Pulser</p>

            <p className="use-desc">
              Like Zapper, Pulsar is also used to kill harmful viruses,
              bacteria, fungi and parasites, tapeworm, ringworm, roundworm etc.
              hidden in the body. The zappers shown in the picture (Indian
              zapper delux) when put on the pulsar mode, it creates a 50% duty
              cycle square wave (non-sinusoidal wave) of double voltages of +30V
              and -30V. You can use it at frequencies of 4Hz, 16Hz and 100 Hz
              respectively. To kill parasites, use pulsar at all three
              frequencies for 10-10 minutes each for approx. 30 minutes, three
              times a day. You can use the coil attached with pulsar anywhere on
              the body, except head and face. Pulsar can be used at body parts
              where the current of the Zapper doesn't reach and parasites such
              as lymph system, stomach and intestines can be killed.
            </p>
            <a href={pdf} download>Click Here For pdf Book</a>
          </div>
        </div>

        <div className="step2">
          <div>
            <img src={proImg2} alt="pro-image" width="100%" />
          </div>

          <div>
            <p className="use-title">How To Use Silver</p>
            <p className="use-desc">
              Colloidal Silver is made by mixing micro silver particles into
              water. Colloidal are minute particles of the mettle which, after
              mixing in any liquid matter (such as water), neither dissolve nor
              develop any ionic compound. These microparticles of silver do not
              drown in the water but keep floating. Generally ionic silver,
              silver colloidal, ionic silver compound or silver protein present
              in pure water is called colloidal silver. It is absolutely pure
              silver mixed water.
            </p>
            <a href={pdf} download>Click Here For pdf Book</a>
          </div>
        </div>
      </div>
    </div>
  );
}
