import React from "react";
import pro from "../assets/images/product1.jpg";
import "../assets/css/product.css";

export default function OurProduct() {
  return (
    <div className="product">
      <div className="p-title">
        <h1>Product</h1>
      </div>

      <div className="product-img">
        <div>
          <img src={pro} alt="product image" width="100%" height="100%" />
        </div>
        <div>
          <h3>Description</h3>
          <p>
            <strong>Parasite Cleanse With Pulsars</strong>Pulsar is a strong
            medium to kill parasites. It is used to mobilize lymph systems and
            ill pathogens (parasites, bacteria, virus, fungi, yeast etc.) hidden
            in the body. Pulsar kills the parasites living your body with the
            help of magnetic pulse.
          </p>
          <p>
            <strong>How to use pulsar?</strong>
            Like Zapper, Pulsar is also used to kill harmful viruses, bacteria,
            fungi and parasites, tapeworm, ringworm, roundworm etc. hidden in
            the body. The zappers shown in the picture (Indian zapper delux)
            when put on the pulsar mode, it creates a 50% duty cycle square wave
            (non-sinusoidal wave) of double voltages of +30V and -30V. You can
            use it at frequencies of 4Hz, 16Hz and 100 Hz respectively. To kill
            parasites, use pulsar at all three frequencies for 10-10 minutes
            each for approx. 30 minutes, three times a day. You can use the coil
            attached with pulsar anywhere on the body, except head and face.
            Pulsar can be used at body parts where the current of the Zapper
            doesn't reach and parasites such as lymph system, stomach and
            intestines can be killed.
          </p>

          <button className="btn btn-success">Buy Now</button>
        </div>
      </div>
      <div className=' container description'>
      <h3>Description</h3>
        <p>
          <span>Parasite cleanse with Zapper</span>
          Zapper is an electric tool, which generates a fixed (but very low)
          volume of current. Many recent studies reveal that applying minute (9
          volt or lesser) current directly on the human body kills different
          types of viruses and parasites and evicts out of the body through the
          waste removal system of the body. Eviction of such parasites increases
          the immune system of the body to a surprising extent. Consequently, we
          recover very fast. We start feeling entirely fresh.
        </p>
        <p>
          It is notable that the negative "ions" built from electrical current
          (or magnet current) do this important job of killing parasites. Zapper
          works on this principle only. In the zapping process when electric
          current is applied on the body, the cysts of the parasites hidden in
          safe places of the body get the shock and they start dying. They turn
          into micro particles and their elements, which are beneficial for the
          body, gets absorbed and harmful.
        </p>
        <p>
          Elements, such as gall-bladder stones etc. are expelled from the body
          through the waste removal process.
        </p>
        <p>
          <strong>How does Zapper work?</strong>
          Every living being realizes its existence through dissemination of
          different frequencies just like frequencies that get aired from radio
          stations. Zapper creates a frequency that equals the frequency of the
          parasites hidden in the body, and thus kills them by making them
          inactive. The current generated by Zapper is only as much as it is
          necessary to kill parasites. It doesn't do any harm to the human body.
          You can zap at frequencies of 2128 Hz, 10 KHz or 30 KHz in the Zapper
          given here. Every frequency has been set for seven minutes in the
          machine; which it can be zapped upon.
        </p>
        <p>
          The current released at a fixed voltage and frequency by Zapper makes
          the parasites numb, which affects their capacity to hide from white
          blood cells. Thus it becomes easy for the white blood cells to find
          them. They treat them as foreign objects that are harmful to the body,
          hence, attack on them and kills them whether they are parasites or
          bacteria; or viruses or fungi! This complete process of Zapper takes
          approx. an hour of time. After that, the white blood cells surround
          these dead foreign objects and expel them out of the body through
          urine or stool.
        </p>

        <p>
          How to zap? <strong>How to zap?</strong>
          Take two cotton clothes or napkins before starting the zap process.
          Rinse them in salt mixed water. Roll each of these cotton clothes
          drenched in salty water on each of the copper pies. It makes the flow
          of the electric current better. Besides, the current generated by the
          Zapper is so low that it would hardly reach the body if the clothes
          are not drenched in salty water.
        </p>

        <p>
          Thus, you get ready for zapping and attach the Zapper with electricity
          through a power source.  Now switch on the power of the Zapper. 
          Hold one copper pipe in each hand tightly, as shown in the picture.
          Remember - the copper pipes should not touch each other.  Hold both
          of these pipes like that for seven minutes and zap at a frequency of
          2180 Hz.  Now interchange copper pipes of each hand means shift the
          pipe of the left hand to the right hand and the pipe of the right hand
          to the left.  Again, hold both the pipes tightly for seven minutes
          and zap at a frequency of 2180 Hz.  Now switch off the power of the
          Zapper. Leave the copper pipes and let both the hands rest for seven
          minutes, drench the napkins/cotton clothes again in saltwater and
          rinse them well.  Again switch on the power of Zapper, and zap for a
          new frequency of 10KHZ for seven minutes.  Interchange the copper
          pipes in both the hands and zap again on 10KHZ frequency for seven
          minutes.  Again, take a break for seven minutes as earlier and zap at
          a new frequency of 30KHZ for two rounds of seven minutes each. It will
          be the third and last set of your zapping process.  Exercise the
          entire process thrice a day, for seven days.
        </p>
        <p>
          {" "}
          <strong>Note:</strong> I have zapped the copper pipes on my armpits,
          neck, tongue, knee and ankles too and have observed better results.
          Actually, the skin of these parts of the body being soft, current
          flows in the blood more effectively.
        </p>
        <p>
          <strong>Why should it be zap thrice every day?</strong>
          Many small parasites and innumerable viruses are hidden in the large
          parasites present in the human body. When we zap the first time, it,
          of course, kills the large parasites but the parasites, egg, larva and
          pupa within these parasites stay unaffected by the electricity and
          come out after some time.
        </p>
        <p>
          Zapping twice and thrice kills egg, larva and pupa completely with
          small parasites. Therefore, it is advised to zap thrice every day, at
          different times.
        </p>

        <p>
          <strong>
            {" "}
            Parasite cleanse with Colloidal Silver (Silver water)
          </strong>
          Parasite cleanse with Colloidal Silver (Silver water) Colloidal Silver
          is made by mixing micro silver particles into water. Colloidal are
          minute particles of the mettle which, after mixing in any liquid
          matter (such as water), neither dissolve nor develop any ionic
          compound. These microparticles of silver do not drown in the water but
          keep floating. Generally ionic silver, silver colloidal, ionic silver
          compound or silver protein present in pure water is called colloidal
          silver. It is absolutely pure silver mixed water.
        </p>
        <p>
          <strong>Medicinal use of silver</strong>
          Silver compounds have been used as a medicine since ancient times.
          Liquid form of silver nitrate was used for the first time in 1880 to
          protect eyes of newborns from infection. Silver creams have been in
          use as antibiotics in burn and trauma centers globally for more than a
          hundred years. It is used very much in Ayurvedic and Unani medicines
          too. Colloidal silver of 5PPM* (Particles Per Million) density or more
          is very effective in killing infectious bacteria. Till before 1938,
          allopathic doctors used colloidal silver very much as an antibiotic.
          It was effective but costly too. Therefore, by the fourth-fifth decade
          of the 20th century, Sulfa-drugs, penicillin etc. were put to use,
          which were economical and faster in effect on patients.
        </p>
        <p>
          <strong>How does Colloidal Silver work?</strong>
          When fungi, virus, bacteria and other single cell pathogens come into
          contact with colloidal silver, it deactivates their oxygen metabolism
          capacity. Pathogen dies within a few minutes after it and expelled out
          of the body through the immune system, lymph gland and other waste
          removal organs of the body.
        </p>
        <p>
          <strong>
            How colloidal silver is better than modern antibiotics?
          </strong>
          Modern antibiotics kill even enzymes beneficial for the body while
          silver colloidal affects only single cell pathogens. Another drawback
          of conventional antibiotics is that its ever use changes composition
          and jeans of single cell bacteriaand they draw power from resistance
          from antibiotics. Not any form of colloidal silver or silver does so
          and bacteria get killed completely. Another peculiarity of colloidal
          silver is that it does not react with any other medicine in any
          manner. Therefore other necessary medicines can also be consumed along
          with it. Colloidal Silver does not create any toxin in the body. It
          does not react with anything except with enzymes that assist in oxygen
          metabolism process of oxygen.
        </p>
        <p>
          <strong>Dose</strong>In order to kill parasites and pathogens out of
          the body, start taking 50ml of colloidal silver every day. After four
          days, make it 20ml for six weeks. Dose can be reduced depending upon
          weight (specially in case of children). After that, repeat the same
          procedure after an interval of a few days. For a good and healthy
          physique this exercise should be practiced for lifelong; with some
          breaks in between. This is the best medicinal and life-saving tonic in
          the world.
        </p>
        <p>
          In order to kill parasites and pathogens out of the body, start taking
          50ml of colloidal silver every day. After four days, make it 20ml for
          six weeks. Dose can be reduced depending upon weight (specially in
          case of children). After that, repeat the same procedure after an
          interval of a few days. For a good and healthy physique this exercise
          should be practiced for lifelong; with some breaks in between. This is
          the best medicinal and life-saving tonic in the world.
        </p>
        <p>
          <strong>Use</strong>
          Colloidal silver is used either orally or through enema. It gets
          absorbed by the intestines. After that it reaches cells through blood.
          Within 3-4 days, the volume of silver grows so much in the tissues
          that it can start work repairing cells and free the body of parasites.
          It takes the kidney and lymph system 3-4 days to expel the silver
          deposited in tissues out of the body which is sufficient time to show
          its therapeutic effect on the body.
        </p>
        <p>
          Colloidal silver is very effective not only in treatment but also in
          the prevention of the diseases.Its intake can save you from cold, flu
          infections caused by bacteria, virus, fungi etc. and other ailments
          which you don't know of. You must have heard that kings and
          Shekh-Nawabs stayed young forever. Silver was one of the reasons. They
          always ate their food in silver pots. Thus their body used to get a
          constant supply of silver, which kept their bodies protected from
          diseases. Their bodies did not have to spend energy on combating with
          ailments and it was used to keep the body healthy instead. We might
          not know which infection we might catch in this crowded age.
          Therefore, regular intake of colloidal silver works as a safety guard
          for you.
        </p>

        <p>
          Every year people get infected with different types of infections by
          consuming contaminated water. Mixing only 50ml colloidal silver can
          clean five liters of water.
        </p>

        <p>
          Whether it is a sinus related problem or sore throat or blocked
          nostrils; or infection of an infant's eyes – colloidal silver is fully
          safe and beneficial in all these conditions. Using it externally on
          skin problems such as itching, eczema, burns, cuts, boils etc. cures
          them faster. Bacteria is a big reason behind body odor. This problem
          can be cured by spraying silver water. Use of colloidal silver is a
          perfect remedy for burn wounds. It not only fills the wound faster but
          also reduces signs of burn. Regular use of colloidal silver can save
          you from different types of severe infections, and stay young for long
          in fact.
        </p>

        <p>
          <strong>Product Quality</strong>
          The best colloidal silver is the one which is made without any
          chemical reaction, i.e. the one made from colloidal silver maker. In
          this process silver particles remain in water but do not dissolve.
          Pure colloidal silver is cloudy white in color (like white cloud).
          Therapeutic quality of silver water depends upon its PPM (density).
          Colloidal silver of three or five PPM is as effective in killing germs
          as the densest silver water is.
        </p>
        <p>
          <strong> Conclusion</strong>
          Parasites germinate and develop in a very specific environment. It
          cannot live without that condition. We can stop development of
          parasites if we could make our body healthy by taking appropriate food
          and cleansing therapy. We should cleanse colon and parasites, take
          healthy food, say a big 'NO' to junk food, wash hands before taking
          food, after using washroom and after changing diapers of children.
          Parasites can be defeated by improving our hygiene habits; there is no
          second opinion about it.
          <p>
            <strong>Advantages of pulsar, Zapper and colloidal silver</strong>
            Pulsar, Zapper and colloidal silver not only help you get rid of
            parasites, but also help you get over diseases caused by them and
            achieve following positive changes in our body:  Quick relief from
            acnes  Improved movements of joints  Relief from chronic pain 
            Quick recovery from burn-cut wounds etc.  Tapeworm in stool after a
            week's time  Improvement in respiratory and sinus process  Body pH
            level balance (in most of the cases)  Reduction in redness of eyes
             Recovery from flue and cold and cough  Cleansing of metals and
            toxins deposited in body  Positive feeling, clear thinking and deep
            sleep  Get rid of depression and migraine  Get rid of "PMS" means
            pre-menstrual problems  Benefit in psoriasis  Relief from
            ringworm, itching and shining skin  Relief in ear pain, tooth pain
             Shrinking and elimination of tumor and warts  End of fungi such
            as yeast and candida  Relief from dandruff  Relief in ulcer
          </p>
          <h3>Clearing the doubts / FAQs</h3>
          <p>
            <strong>1. Is use of Zapper fully safe?</strong>
            Yes, it is safe; but pregnant ladies and people with pacemakers
            should avoid use of Zapper. In the initial days of using Zapper, one
            might not feel well because of cleansing of parasites, but you will
            be okay in an hour or two.
          </p>
        </p>

        <p>
          <strong>2. Can one feel electric shock while using Zapper?</strong>
          No one feels shock with a 9-volt battery or power supplied with the
          help of an adopter (here input voltage is 9 volt and output voltage
          lowers further).
        </p>
        <p>
          <strong>3. What is the right time to use Zapper?</strong>You can use
          Zapper anytime as per your convenience.
        </p>
        <p>
          <strong>
            4. What to do when copper pipers (which we hold during zapping) gets
            black?
          </strong>
          Their blackening is natural. It does not affect the zapping process
          and causes no harm at all. You can clean them with Scotch Brite (or
          any other scrub) and soap.
        </p>

        <p>
          <strong>
            5. Can copper pipes be held in any hand during zapping or there is
            some specific way to hold them?
          </strong>
          You can start zapping by holding any pipe in any hand. Also, you have
          to keep interchanging copper pipes between two hands. Just note that
          both the pipes must not touch each other once the power switch is on.
        </p>
        <p>
          <strong>
            6. In your view, is it appropriate to use Zapper, pulsar, and
            colloidal silver together for two weeks?
          </strong>
          I believe it to be appropriate and for better results, one must
          cleanse kidney and acidities before using them. Then cleanse parasites
          and, it is more than better if you could cleanse liver too immediately
          after cleansing of parasites. After two weeks you will feel like a
          young lad full of energy instead of the old tired person. One more
          thing, when you use both Zapper and pulsar together, then one week
          course is sufficient instead of two.
        </p>
        <p>
          <strong>
            7. Will it impact negatively on my health if I use Zapper, pulsar
            more than the time you recommend?
          </strong>
          There is no harm in regular use of Zapper, pulsar. But it costs extra
          money and time; which everyone lacks. That is why I never advise the
          regular use of Zapper. And you don't need that. Once parasites have
          been destroyed, re-germination takes time. In such a situation, you
          can repeat it when you need it. Yes, you can keep taking colloidal
          silver water regularly after some break.
        </p>

        <p>
          <strong>8. Can I use Zapper while cleansing kidney or liver?</strong>
          Of course, and you will get better results by cleansing complete
          parasites before cleansing the liver.
        </p>
        <p>
          <strong>9. I have a zapper. Can it also be used as a pulsar?</strong>
          Zapper and pulsar are two different instruments with different
          functions. They work on different frequencies. Their input current is
          different. Their output waves are also different. They, of course, are
          complementary to each other. However, now Indian Zapper Deluxe is
          offering pulsar and Zapper and colloidal silver in one instrument.
        </p>
        <p>
          <strong>
            10. Can I use distilled water to prepare colloidal silver water?
          </strong>
          You can use distilled water, but it is not going to serve any specific
          benefit. Be it tab water, purified water or mineral water or spring
          water – all are equally suitable for preparing colloidal silver water.
        </p>

        <p>
          <strong>
            11. What is the life of silver rods used in making colloidal water?
          </strong>
          It depends upon the method of preparing colloidal silver water.
          However, one pair of 5-6 inch silver rod can make approx. 5000 glass
          of silver water.
        </p>

        <p>
          <strong>
            12. Do we mix salt while preparing colloidal silver water?
          </strong>
          Don't mix anything while preparing colloidal silver water, salt never.
          Mixing salt can, of course, hasten the process of colloidal silver,
          but it adds many impurities in the water, which diminish the impact of
          colloidal silver.
        </p>
        <p>
          <strong>
            13. What is the right method of making colloidal silver water?
          </strong>
          During the process, keep the colloidal silver maker on until water
          becomes cloudy white. It takes approx. 10 to 20 minutes in it.
        </p>
        <p>
          <strong>
            14. How much colloidal silver should I make in one attempt?
          </strong>
          There is no limit. You can make as much colloidal silver as you want.
          Generally, people make only one glass of silver water in one attempt,
          divide it in four doses and finish it during the day. Remember that
          the colloidal silver is to be stored in coloured glass water as it
          becomes black by reacting with light in a transparent bottle.
        </p>
        <p>
          <strong>
            15. Eating food in silver pots or taking colloidal silver water,
            what is better?
          </strong>
          It might take a considerably long time to realize health benefits by
          eating food in silver pots, while colloidal silver benefits quickly.
        </p>
      </div>
    </div>
  );
}
